### ISSUE TITLE
Feature request: !remindme text

### ISSUE THREAD

**Issue by sinus-x** [Czechbol/Amadeus#21]
~Include message in the embed, do not just link it -- it may have been deleted or user could have lost access.~

Edit: The message is contained if it was separated by newline. The bot should check if the message contains a newline -- if it does not and there are letters at the end, maybe it should try to separate it?

**Comment by czechbol** [comment]
I'm not sure how I'd deal with the datetime and message on the same row. I have to think about it.

**Comment by czechbol** [comment]
resolved in 783047ef8567016b5beac72a37c2f10733167a51
