### ISSUE TITLE
"Librarian" cog

### ISSUE THREAD

**Issue by sinus-x** [Czechbol/Amadeus#3]
Use [Rubbergoddess](https://github.com/sinus-x/rubbergoddess)' Librarian cog commands (`nameday`, `weather`).

Adapt [Masaryk's Math cog](https://github.com/zloutek1/MasarykBOT/blob/452779efb3143ffc998d6a76f0fd3319ab90ad89/cogs/math.py):
- `latex` command to allow printing equations
- `graph` command to show equation plots

_This issue is migrated from our main bot, [Rubbergoddess](https://github.com/sinus-x/rubbergoddess/issues/46)._

**Comment by czechbol** [comment]
Implemented as separate cog
